### ISSUE TITLE
Upgraded from 1.3 to 1.4 and lost native games and pocketSNES saves

### ISSUE THREAD

**Issue by valzi** [eduardofilo/RG350_adam_image#179]
EDITED:
I also lost my pocketSNES saves and all of the game files from the internal SD card.

I followed the upgrade procedure properly.

Is there a way to restore the missing files?

**Comment by valzi** [comment]
Upon further inspection, all of my Cannonball files are missing from the internal SD card.

**Comment by m45t3r** [comment]
Not sure if this is clear for everyone, but the "upgrade" process you basically format and reinstall a newer version. The `PyBackup` step is important because every file that you want to keep between upgrades needs to be added to the `PyBackup` list before update. It is pretty easy to add your own entries too: https://github.com/eduardofilo/RG350_py_backup#configuration.

It could be argued that `PocketSNES` not being in the default `PyBackup` configuration is a mistake, but every other game that you add manually and you want to keep also need to be added to `PyBackup` manually. So if you didn't add it, you pretty much lost those files, sadly.

**Comment by eduardofilo** [comment]
Perfect answer @m45t3r.
I certainly forgot to add PocketNES to the Py Backup setup when it was added to the image. In general the image is very focused on RetroArch. I leave open the issue to incorporate that emulator to Py Backup.

@valzi I'm sorry what happened to you. In the future the best advice is to flash onto a different card and keep the old one untouched for a while in case any files are missing. I'm going to incorporate that recommendation into the upgrade instructions.

**Comment by valzi** [comment]
Thanks. That's a lot of hours lost, so I hope you can make a new video or just type out instructions. I wouldn't mind contributing a written version if you like.

Also, I found an option in retroarch to place saves AND save states in content folders. Are there any reasons to not do this? Seems like a way to separate at least part of the problem from the internal SD card.

I looked at the py backup page that m45t3r linked and it defaults to including pocketsnes in the list. I wonder why it's not working in Adam Image?

**Comment by eduardofilo** [comment]
> Thanks. That's a lot of hours lost, so I hope you can make a new video or just type out instructions. I wouldn't mind contributing a written version if you like.

At this point I am convinced that no matter how much I write, these problems will not be completely avoided. These gadgets are not a household appliance and require a lot of dedication to live with them without problems. The image is a bit contradictory in that aspect because it aims to make things easier, but it is a trap for many people, so I don't know if it was a good idea.

> Also, I found an option in retroarch to place saves AND save states in content folders. Are there any reasons to not do this? Seems like a way to separate at least part of the problem from the internal SD card.

I assume you mean that most directories can be configured to remain in the external card. It can also be done with Linux symbolic links. In general I thought to use the external card only for the contents (ROMs, BIOS, Ports, backups). I thought about moving also configs, but in the end I decided to leave them in the internal file system and deal with them through backups. That also gives me possibilities to improve the settings by keeping them inside the image. Maybe I should separate savestates from configuration and pass the first ones to the external like you say, but that would surely bring a whole new set of problems.

> I looked at the py backup page that m45t3r linked and it defaults to including pocketsnes in the list. I wonder why it's not working in Adam Image?

That's because the file that @m45t3r has put is the default configuration of Py Backup, but in Adam I cut it to show only what was installed in the image. As we have mentioned before, it was a mistake not to restore PocketSNES config (and some more that I have seen that are missing) when I installed it.

**Comment by valzi** [comment]
Thanks for explaining everything.

> I assume you mean that most directories can be configured to remain in the external card.

No, I was actually thinking about a setting in Retroarch. There's a setting that tells Retroarch to store save states and regular save files alongside the roms instead of inside of the Retroarch directory.

**Comment by eduardofilo** [comment]
I don't like that option. The mixture of files in directories that usually contain so many files does not seem like a good idea to me. But thanks for the suggestion.

**Comment by eduardofilo** [comment]
Fixed in v1.4.1.
