### ISSUE TITLE
RG280V Failing to boot, SQUASHFS errors 

### ISSUE THREAD

**Issue by gibb3h** [eduardofilo/RG350_adam_image#250]
Hello, I am having issues when trying to boot the kernel, I have tried flashing 1.4.2 with both balena and win32 disk imager and have run the .bat file for the correct device.

usually on boot I get stuck in console following  a SQUASHFS error zstd decompression error: 14, if I reset I occasionally get to the opendingus loading bar but then it hangs.

![image](https://user-images.githubusercontent.com/4102650/169977392-26e32a21-bbd3-46d6-8870-9125f696f867.png)

![image](https://user-images.githubusercontent.com/4102650/169978289-2d0a7c2a-46a3-4556-887e-b78cc48cd229.png)

I have reflashed the same SD with the stock firmware and that works without issue so I don't think it is an SD card issue?

I have also tried removing the battery and restarting but that doesn't seem to help either.

are logs created at boot? are they accessible in any way?

How long should first boot take, I have left it for 30 minutes and the progress bar does not change

**Comment by eduardofilo** [comment]
In some machines, different systems produce different behaviours. I understand that because of having marginal hardware that interferes badly with some of the ways of managing the hardware of those systems. We don't develop the system here, we just install it along with other pieces of software that may also fail, after all this is homebrew. The only thing I can think of to tell you is:

1. Try different SD cards.
2. If you really want to get to the bottom of the issue, check if the problem occurs on clean ODbeta by installing [this update](http://od.abstraction.se/opendingux/latest/gcw0-update-2022-02-13.opk) over the stock firmware on the same card that gives you the problem. If that is the case, report the issue in the OpenDingux repository. But frankly I don't recommend you doing that. I think it's a particular problem with your unit.

The link I put before with the ODbeta update corresponds to the version installed in Adam, but if you are going to open an issue for your problem in that repository, it would be better to try before with the latest released version that you can find here:
https://github.com/OpenDingux/buildroot/suites/5911427256/artifacts/201765446

To download the above file you need to be logged in to github.

**Comment by gibb3h** [comment]
Thanks for your response, I could not update using either of those versions of OD (got "Failed to update rootfs!" error inside the OS Updater app)

I've ordered a new SD card so I'll try with that, if not I guess i'm stuck on stock as I doubt I can return the device to AliExpress!

Gib

**Comment by eduardofilo** [comment]
Try flashing this before using the ODbeta OPK updater:
https://rs97.bitgala.xyz/RG280V/rg280v-clean-stock.img.7z

It should work. I have done in my RG280V many times.

**Comment by gibb3h** [comment]
As an update, I have now tried 3 different SD cards, the behaviour is the same on all of them, I can get 1.4.2 to boot maybe 1 time in 10, but it is very unstable even when it does manage to boot, games crash back to SimpleMenu, the system randomly reboots itself.

I also can still not get OD to update from stock, I am using the img you linked to, at this point I can only assume that it is a hardware issue, primary sd card read/write seems to be very temperamental.

I'll close the issue as I don't think there is any issue your side, thanks for your help

**Comment by eduardofilo** [comment]
OK. Good luck with the warranty support.

**Comment by gibb3h** [comment]
ha, it works fine with stock firmware so I'm not going to bother trying to get the AliExpress seller to take it back...
