### ISSUE TITLE
Cannot set keyboard in crocods.ini

### ISSUE THREAD

**Issue by mtrevor** [eduardofilo/RG350_adam_image#293]
### What happened?

I'm trying to change the `key/emulation` setting in `/media/data/local/home/.crocods/crocods.ini` from 3 to 1 in an attempt to switch the keyboard input from azerty to qwerty. However, when I run CrocoDS again, the input is still azerty and the ini file is set back to 3.

I couldn't see an option in CrocoDS to set the keyboard type and couldn't find much in the way of CrocoDS docs. Are configs in the home folder modifiable?

Cheers.

### Device

RG280V

### Version

v2.1

**Comment by a-dekker** [comment]
Can't really help you, but I can confirm that the key -> emulation value is always reset to '3'

Unfortunately the code at https://github.com/redbug26/crocods-core is outdated so I can't tell why and what this option is supposed to be doing.

The standalone version http://crocods.org/crocods_20200115.opk has a proper qwerty keybinding, so it seems not related to this key setting. 

Certain config values can be changed, sound enabled/disabled works for example.

You could try to open an issue at https://github.com/redbug26/crocods-core/issues or somewhere at libretro perhaps.

**Comment by eduardofilo** [comment]
Good answer @a-dekker.

I have tested and in my case the qwerty keyboard appears whether or not that setting is present (in the newly installed image that configuration file contains nothing but comments).

![screenshot001](https://user-images.githubusercontent.com/2923728/189489612-06388282-f8ae-4b36-a067-15756e600cb2.png)

In any case I turn the issue into a discussion since it is an emulator problem.
