### ISSUE TITLE
exFAT TF2 RG280V no write permissions

### ISSUE THREAD

**Issue by cryptoluks** [eduardofilo/RG350_adam_image#301]
### What happened?

Hello. New user here, thanks for this great image.

It works flawlessly on my RG280V using a FAT32 formatted SD card in the TF2 slot. However, using a exFAT formatted SD card in TF2 slot, only read access is possible. I noticed it, while creating a new favorite and launching it from the favorites menu. The device will reset and favorites are gone as no write to the fav file was possible.

I know, the new exFAT support is relatively untested, therefore I switched back to FAT32 for the time.

To reproduce, simply flash a fresh system with the appropriate kernel, and format the second card in MBR scheme and a single exFAT partition without a label. Using the latest release (v2.1).

Thanks again for maintaining this project. Have a nice day.

### Device

RG280V

### Version

v2.1

**Comment by a-dekker** [comment]
Did not test myself, but in this discussion the experience is that writing is working in exFAT: https://github.com/eduardofilo/RG350_adam_image/discussions/226
Perhaps check the posts in that discussion first.

**Comment by eduardofilo** [comment]
Same here, I've been using exFAT on the EXT card for a while and haven't had that problem. I would have to see it to analyse and give an answer, but in the meantime I'd say try formatting the card with a different procedure. If you can connect via SSH it would also help to see the output of the `dmesg` command. Sorry for the delay in replying.

I'm closing the case because I consider this is a particular problem, but we can continue to look into your case here if it can help.
