### ISSUE TITLE
Retroarch overlay directory is incorrect and not able to be changed

### ISSUE THREAD

**Issue by zomgugoff** [eduardofilo/RG350_adam_image#304]
### What happened?

Retroarch on-screen overlay default directory appears to be pointed at /opk instead of `~/.retroarch/overlay`. The option to change this is missing from the Directory settings in the included version of Retroarch. I added "overlay_directory = "~/.retroarch/overlay" to ~/.retroarch/retroarch.cfg, but the setting is apparently not read at all.

### Device

RG350M

### Version

v2.1

**Comment by a-dekker** [comment]
It is discussed at https://github.com/eduardofilo/RG350_adam_image/discussions/106

You are right the directory points to /opk. But I did some tests with a custom location to no avail, overlays seem not supported as eduardofilo alread mentioned in the discussion. It requires some hardware features that may not be available or implemented in RA for OD-beta.

The overlay option is also disabled in the rg350_odbeta makefile: https://github.com/libretro/RetroArch/blob/master/Makefile.rg350_odbeta#L86
Still having overlay menu options by default makes it confusing for everyone for sure.

A positive side-note is that the aspect ratio on opendingux devices is not widescreen, making the need for additional bezels less prominent.

**Comment by zomgugoff** [comment]
I was trying to use overlays for basic scanlines as the video filters are too slow.

**Comment by a-dekker** [comment]
That would have been a cool use case I did not think of yet!

**Comment by Sakitoshi** [comment]
you are losing your time.
retroarch doesn't support overlays on opendingux.
best you can do is use filters, located in the video settings.
i use them myself for handhelds, since they are lower resolution it works fine.
but for home consoles the scanline effect doesn't always look good. snes is the prime example where if you decide to use scanlines, in order to look good you have to use integer scaling, but if you do that then you end up with wrong aspect ratio.

**Comment by eduardofilo** [comment]
I'm reading this issue late, sorry, but I see it's already been clarified that there is no support for overlays in RetroArch for OpenDingux. I close the issue.
