### ISSUE TITLE
Vibrate/Rumble does not work on Pocketgo V2

### ISSUE THREAD

**Issue by V4NT0M** [eduardofilo/RG350_adam_image#324]
### What happened?

Using the PocketGo V2 Kernel I get no vibration in the RG350 test app or in emulators.

If I use the RG350 Kernel the rumble works but this causes other issues.

### Device

PocketGo2 v2

### Version

v2.1

**Comment by eduardofilo** [comment]
I'm sorry but I don't develop the firmware, I just install it on the image. The problem should be reported to the OpenDingux beta repository. Although before doing so I recommend that you do a clean installation following the procedure established by its authors and try one of the latest versions, since the problem you have might already be solved.
