### ISSUE TITLE
PlayGo/PocketGo 2 v2 issues

### ISSUE THREAD

**Issue by theVanZan** [eduardofilo/RG350_adam_image#35]
I purchased a black PlayGo PG2 from the Wolsen store on AliExpress last month. It arrived a few days ago and initially I tried the latest Adam image. However I could not navigate the menus properly. I kept seeing "Loading" appear at the bottom right and flashing continuously even when I tried to access Dingux Commander for example.

I used the stock image on a good Micro SD and updated it with the OD beta and have no problems. I guess I must be doing something wrong since there are no other reports?

**Comment by eduardofilo** [comment]
This problem is relatively common and can be caused by various reasons. If you've successfully flashed the INT card, it should boot. If it does not, it will be due to corruption of the INT card (for having pressed Reset for example) or because there is some kind of problem on the EXT card. Try booting with the EXT card removed. If it does not start, the first thing to try is to delete the file `/media/data/local/home/.simplemenu/last_state.sav` for which you will need to connect by SSH or SFTP.

If that doesn't work or you don't know how to do it, you'll have to re-flash the image on the internal card. If you end up doing that, do the first boot without the EXT card inserted. Then remove SimpleMenu as the default launcher and you will have more opportunities to analyze the problem from GMenu2X.

**Comment by brainfrz82** [comment]
Ran into the same problem, someone on youtube recommended to select the RG350/p model in the kernel selection. After i did it runs fine as far as i can tell.

**Comment by eduardofilo** [comment]
Well, I only installed the last distribution of OpenDingux Beta firmware which was where the problem was actually solved. But I'm glad that it works well for you now. Thanks for the confirmation.
