### ISSUE TITLE
Screen tearing on FBA games

### ISSUE THREAD

**Issue by GamerWadie** [eduardofilo/RG350_adam_image#36]
Brilliant work guys, only thing I've noticed is screen tearing using the FBA emulator, thankyou

**Comment by GamerWadie** [comment]
Forgot to mention this is on both the og rg350  and the rg350p

**Comment by eduardofilo** [comment]
Thanks for your comments.
Please, mention one example to test.
I suppose that the setting that may be involved in this problem is the `Vertical sync`, which is effectively disabled by default in the image. Open FBA UX from GMenu2X and follow this route:
Main settings (start key) > Default ROM settings > Default Run Game settings > Vertical sync

Change it to On and see if the problem improves.

**Comment by GamerWadie** [comment]
Thankyou yes I turned it on and it now works perfectly,RegardsAndrewOn 25 Sep 2021 19:18, Eduardo Moreno ***@***.***> wrote:
Thanks for your comments.
Please, mention one example to test.
I suppose that the setting that may be involved in this problem is the Vertical sync, which is effectively disabled by default in the image. Open FBA UX from GMenu2X and follow this route:
Main settings (start key) > Default ROM settings > Default Run Game settings > Vertical sync
Change it to On and see if the problem improves.

**Comment by eduardofilo** [comment]
Vertical sync enabled by default in 1.3 release of the image.
