### ISSUE TITLE
RG280v - 1.3.1 not working

### ISSUE THREAD

**Issue by hxberto** [eduardofilo/RG350_adam_image#76]
After installing 1.3.1, the RG280v does not boot. Stays in the initial screen.
I tried both a fresh install and upgrade from 1.3, both do not work.
1.2 and 1.3 are ok.

**Comment by eduardofilo** [comment]
I assure you that the 1.3.1 image works on that console model. It is precisely my main device and on which I do most of the tests. In addition, I would have received a lot of complaints since the RG280V is one of the devices where Adam is installed the most.

Have you followed the steps indicated in the documentation section that I indicate?
I understand that yes, since you say that versions 1.2 and 1.3 worked well for you, but just in case.

https://github.com/eduardofilo/RG350_adam_image/#fresh-installation

**Comment by hxberto** [comment]
Hi! I got it working, but only by manually placing the RG280v files after the flash. Don't know why but the .bat file opens but I don't think it's coying the files correctly. I'm using W11.
But it's solved!

**Comment by eduardofilo** [comment]
May be, I could only test it on W10.
I'll be watching in case it happens to more people. Thanks.

**Comment by ng01near** [comment]
hi! i got the same problem. how did you fix it? thanks:(
