### ISSUE TITLE
Request: Support for external microSD card with a label

### ISSUE THREAD

**Issue by brunns** [eduardofilo/RG350_adam_image#8]
Using a Mac, it doesn't seem to be possible to format an SD card without a label. (If I'm wrong about that, I'd be delighted to hear about it!) Is there some way to configure Adam to use such a microSD card?

**Comment by brunns** [comment]
Alternatively, perhaps it could be possible to have an option to format the card on the handheld device?

**Comment by eduardofilo** [comment]
Actually the "problem" is that the paths on external card get that label, so are unpredictable. When the card has not label, the system adopt the name "sdcard" and insert that name in the paths. So I suppose that you can put that label and the situation will be equivalent.

**Comment by brunns** [comment]
Thanks. That's progress, but it's also impossible to set the volume label to anything lower case, so I still can't get it working.

**Comment by eduardofilo** [comment]
Try this:

https://apple.stackexchange.com/questions/56292/change-label-on-usb-drive-in-osx-terminal

Or borrow a Windows or Linux computer. :-)

**Comment by brunns** [comment]
Hah, thank you, yes, that's one of the things I tried. OSX is stubborn, and that *still* left me with the label in upper case.

Using [iBored](http://apps.tempel.org/iBored/), on the other hand, via [these instructions](http://hints.macworld.com/article.php?story=20090506034709445), **did** work. Terrifying - I'd never use it on a disk with data on it which I wanted to keep - but it worked. Leaving this here in case anyone else has the same problem. Thanks again for your help, and for the work you've put into this.

**Comment by eduardofilo** [comment]
Thanks to you for finding the solution. I am going to include those instructions in the README.

**Comment by plaidman** [comment]
I think the software that @iammeat is suggesting will only format to exFat, which may be incompatible with opendingux. @eduardofilo please correct me if I'm wrong.

**Comment by iammeat** [comment]
@plaidman I just checked and it seems the SD Card Format tool formats different sizes like this:

SD/microSD card: FAT12/16 up to 2GB
SDHC/microSDHC card: FAT32 more than 2GB and up to 32GB
SDXC/microSDXC card: exFAT more than 32GB and up to 2TB

So, the best option is to use the other tools to format the card if larger than 32GB. 

It seems exFAT cards are supported on ROGUE CFW so maybe it's something we can have supported in Adam?  Maybe @Ninoh-FOX could contribute?

**Comment by eduardofilo** [comment]
Any advance in the system will be great, but regarding the image (at least in the current state in terms of the supported formats for the EXT card) we will have to continue looking for a good workaround so that Mac users can format the card in FAT32 without label.

**Comment by retrogamecorps** [comment]
> As it turns out I gave it one more shot and this time I managed to get it set up right. I used Disk Utility to format it FAT32 with a label of 'Untitled'. Then I was able to remove the label with with the fatlabel from dosfstools. The mistake I made before was trying to do this with the card still mounted. Once I unmounted it the fatlabel command worked and removed the label. So basically dumb pilot error on my part.

I'm working on a step-by-step guide for Mac users, but I'm getting stuck at the fatlabel command.  If I try it while the sd card is mounted, I get the "open: resource busy" error, but when I try it unmounted I get "Logical sector size is zero" instead, and then it mounts the card and nothing else happens.  Any advice?

I think the most convenient workaround is to host a blank 128GB SD card image that is properly unlabeled.  Then a Mac user could just flash that image to their card and be done.  It obviously is a very specific use case, and would require the user to only use a 128GB card, but I think it might just be better for the end users who don't want to go through the trouble of installing brew and working in Terminal (or get stuck like me).  I've personally spent an hour on it this morning and I'm deeply frustrated with the process, even as a long-time Mac user!  

Initially I made a very small blank card image (from the smallest card I have, 256MB, but zips down to 99MB), but then I learned that you cannot resize FAT32 partitions on a Mac using Disk Utility because it's not a GUID partition, and using diskutil in Terminal to expand the partition won't work because it requires you to label the partition.  So flashing the 99MB image to a 128GB card just gives you 256MVB of usable space.  Paragon software solutions might have worked but I don't think it's worth asking users to pay $40 to resize one partition.

So I'm in the middle of making the blank 128GB image now, I'll share/host it when it's done.  Hopefully it compresses a lot when I zip it!

**Comment by retrogamecorps** [comment]
Okay, [here](https://mega.nz/file/KAMgSRAC#cZN7Rmu6D2J_2qGE7yVloNo1964d1j6JOBI8_6CSMp0) is the 128GB blank SD card image.  I've also updated [my guide](https://retrogamecorps.com/2021/08/20/rg350-rg280-series-starter-guide/#MacSD2) to provide Mac-specific steps.

**Comment by Asppire** [comment]
> Using a Mac, it doesn't seem to be possible to format an SD card without a label. (If I'm wrong about that, I'd be delighted to hear about it!)

On a Mac: Format an SD card FAT32 with disk utility. Choose MS-DOS(FAT) with a master boot record, then Erase (for some reason I always get an error the first time I try). Name it “U” initially. 

After the SD card is formatted, right click on it in Disk Utility and choose Rename. Then delete the “U” and just type a space and press enter. Eject your card and insert it in your RG350 device with your new Adam image and voila the directory structures will be created for you (the card will have the name “Untitled” when used in a Mac again).

**Comment by retrogamecorps** [comment]
> > Using a Mac, it doesn't seem to be possible to format an SD card without a label. (If I'm wrong about that, I'd be delighted to hear about it!)
> 
> On a Mac: Format an SD card FAT32 with disk utility. Choose MS-DOS(FAT) with a master boot record, then Erase (for some reason I always get an error the first time I try). Name it “U” initially.
> 
> After the SD card is formatted, right click on it in Disk Utility and choose Rename. Then delete the “U” and just type a space and press enter. Eject your card and insert it in your RG350 device with your new Adam image and voila the directory structures will be created for you (the card will have the name “Untitled” when used in a Mac again).

This works like a charm, thanks!  I'll update my guide.

**Comment by eduardofilo** [comment]
@retrogamecorps I steal your workaround description from @Asppire, Russ. Thanks to both.

**Comment by sidewinder42** [comment]
Hi - I've just faced this issue in 2024 (yes, the RG350 still lives!). None of the above solutions worked, but I managed to get fatlabel to work, by acting directly on the FAT partition rather than applying it to the whole disk. For others, here is how I did it:

Installed `dosfstools` using homebrew (you need to install homebrew first if you don't have it):

`brew install dosfstools`

Then I inserted my SD card and formatted it to FAT32 (with any label, in my case I just used the letter U) using the Disk Utility app.

Then I switched to terminal and type:

`diskutil list`

When you do this you should see the SD card and notice it has a substructure of two partitions. In my case it was:

/dev/disk4 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *126.4 GB   disk4
   1:                 DOS_FAT_32 U                       126.4 GB   disk4s1`

We now need to unmount the DOS_FAT_32 partition (not the whole disk). This is labelled disk4s1.

`sudo diskutil unmount /dev/disk4s1`

Then we can use fatlabel to remove the label.

`sudo fatlabel -r /dev/disk4s1`

This worked for me and I hope it works for others.
